### ISSUE TITLE
Add option for nametag to always have full brightness

### ISSUE THREAD

**Issue by Tenuuu** [MicrocontrollersDev/NametagTweaks#1]
Feature like this would make nametags a lot easier to see through walls and such

**Comment by MicrocontrollersDev** [comment]
too cheaty

**Comment by Tenuuu** [comment]
I was more so recommending the option as it's difficult to see name tags through walls with shaders, but fair

**Comment by MicrocontrollersDev** [comment]
yeah i can see why it would be wanted but i also dont want my mod on servers' lists of disallowed mods

**Comment by MicrocontrollersDev** [comment]
Upon further inspection, it seems vanilla already allows this to an extent

![image](https://github.com/user-attachments/assets/89677934-bdb5-4da3-a953-ac36f2401b18)

setting text background opacity to 100% and setting it to show everywhere shows black nametags through walls. 

i wont do exactly what you've asked here. the text on nametags will still be hard to read, but itll be easier to tell that a nametag is in fact there

**Comment by MicrocontrollersDev** [comment]
0e75608 and version 1.3.3
